-- AlterTable
ALTER TABLE `campaigns` ADD COLUMN `active` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `activeRate` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `completed` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `completionRate` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `pending` INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `email_stats` ADD COLUMN `bounceCount` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `bounceRate` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `clickToOpenRate` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `deliveryRate` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `spamCount` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `unsubscribeRate` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `unsubscribed` INTEGER NOT NULL DEFAULT 0;
